CREATE TYPE vax AS ENUM('Female-Spayed', 'Male-Neutered', 'Male', 'Female');

CREATE TABLE IF NOT EXISTS dog(
    DOG_ID serial PRIMARY KEY,
    FACILITY_ID INT NOT NULL,
    GROUP_NUM INT NOT NULL,
    GRAD_DATE DATE NOT NULL,
    DOG_NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    SHELTER VARCHAR(50) NOT NULL,
    BREED VARCHAR(50) NOT NULL,
    CHIP_TYPE VARCHAR(50) NOT NULL,
    CHIP_NUM INT NOT NULL,
    GENDER vax NOT NULL,
    PROFILE_PIC VARCHAR(100) NOT NULL,
    ALT_NAME VARCHAR(50) NOT NULL,
    NOTES VARCHAR(200) NOT NULL,
    ADOPTER_NAME VARCHAR(50) NOT NULL,
    ADOPTER_PHONE VARCHAR(11) NOT NULL,
    ADDR_LINE VARCHAR(100) NOT NULL,
    ADOPT_CITY VARCHAR(50) NOT NULL,
    ADOPT_STATE VARCHAR(30) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    ADOPT_EMAIL VARCHAR(100) NOT NULL,
    FEES INT NOT NULL,
    REVENUE INT NOT NULL);

INSERT INTO dog(DOG_ID, FACILITY_ID, GROUP_NUM, GRAD_DATE, DOG_NAME, AGE, SHELTER, BREED, CHIP_TYPE, CHIP_NUM, GENDER, PROFILE_PIC,
  ALT_NAME, NOTES, ADOPTER_NAME, ADOPTER_PHONE, ADDR_LINE, ADOPT_CITY, ADOPT_STATE, ZIP, ADOPT_EMAIL, FEES, REVENUE)
VALUES(123456, 987654, 14, '2022-11-15', 'Alex', 10, 'Irvine Animal Care Center', 'Husky', 'A', 123, 'Female-Spayed', 'hi', 'Ale', 'Friendly', 'Ben', '11233455678',
'1234 Apple St', 'Irvine', 'California', '92602', 'adoptedadog@gmail.com', 40, 100);